alias l='ls -lh'
alias ls='ls --color'
alias la='ls -la'

alias rld='source ~/.zshrc'
alias fix='vim ~/config/aliases.sh'
alias zfix='vim ~/.zshrc'
alias vfix='vim ~/.vimrc'

alias cc='source ~/config/tmux/start-cc'
alias cw='source ~/config/tmux/start-wc'
alias cf='source ~/config/tmux/start-fc'
alias e='source ~/config/tmux/end'
alias tit='source ~/config/tmux/std-setup'

alias sys='cd ~/hacking/systems'
alias sd='cd ~/hacking/softdev'
alias hk='cd ~/hacking'

alias gp='git push'
alias gl='git pull'
alias ga='git add'
alias gc='git commit'
alias gs='git status -s'
alias gd='git diff --color'
alias gr='git rm'
alias gb='git branch --color'
alias gcl='git clone'
alias gch='git checkout'
alias glg='git log --color'

alias spfy='spotify 2> /dev/null > /dev/null &'
alias groove='vlc ~/music/groovesalad.pls 2> /dev/null > /dev/null &'
alias stm='steam 2> /dev/null > /dev/null &'
alias tmux='tmux -2'

alias homer='ssh -x zane.sterling@homer.stuy.edu'
